env:
  browser: true
  es6: true
  node: true
extends:
  - plugin:react/recommended
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
settings: 
  react:
    createClass: 'createReactClass'
    pragma: 'React'
    version: 'detect'
    flowVersion: '0.53'
rules: 
  semi: [error, always]
